common: &common
  adapter: postgresql
  username: juampi
  password: admin
  host: localhost
  
development:
  <<: *common
  database: railstutorial_development
  
test: 
  <<: *common
  database: railstutorial_test
  
production:
  <<: *common
  database: railstutorial_production
  
